### ISSUE TITLE
Add featured_img_alt to the BlogPost section of etc/schema.graphqls

### ISSUE THREAD

**Issue by rvm-pmis** [magefan/module-blog-graph-ql#17]
featured_img_alt is missing from etc/schema.graphqls in the type BlogPost. Adding this line makes it retrievable via GraphQL:

`featured_img_alt: String @doc(description: "Blog Post Featured image alt text")`

Patch: [magefan.module-blog-graph-ql.add.featured_img_alt.to.graphql.txt](https://github.com/magefan/module-blog-graph-ql/files/8764509/magefan.module-blog-graph-ql.add.featured_img_alt.to.graphql.txt)

**Comment by magefan** [comment]
Thank you for your suggestion @rvm-pmis , this code has been added. And included in new version 2.1.5
