### ISSUE TITLE
Graphql filter IN exception

### ISSUE THREAD

**Issue by luckyraul** [magefan/module-blog-graph-ql#7]
```
{
operationName: blogPosts, query: [Filtered], variables: {filter: {category_id: {in: [okrashivanie, strizhki, pricheski, uhod]}}, pageSize: 4}
}
```

Cardinality violation: 1241 Operand should contain 1 column(s), query was: 
```SELECT `t`.`category_id` FROM `magefan_blog_category` AS `t` WHERE (t.identifier = 'okrashivanie', 'strizhki', 'pricheski', 'uhod')```

**Comment by ihorvansach** [comment]
@luckyraul , we have fixed the issue, the change was made in Blog extension reposiotry
https://github.com/magefan/module-blog/commit/4b8b442af3e74dfd44a906bfdadd376f393e8536

**Comment by luckyraul** [comment]
Thanks, release please

**Comment by ihorvansach** [comment]
@luckyraul , https://github.com/magefan/module-blog/releases/tag/2.9.4 released
