### ISSUE TITLE
Posts sort issue

### ISSUE THREAD

**Issue by luckyraul** [magefan/module-blog-graph-ql#8]
Currently, posts are sorting only by the update_time field, which is not correct. 

Posts should by sorted by publish_time

**Comment by luckyraul** [comment]
https://github.com/magefan/module-blog-graph-ql/pull/9

**Comment by magefan** [comment]
@luckyraul , merged

**Comment by luckyraul** [comment]
@magefan  release also =)

**Comment by ihorvansach** [comment]
@luckyraul , done
